default: &default

  address: "smtp.mailgun.org"
  port: "587"
  domain: "raisingstars.co"
  authentication: "plain"
  user_name: "postmaster@raisingstars.co"
  password: "b14055e1d0756e3ae068c5f34aef1517"
  enable_starttls_auto: true

development:
  <<: *default
